/* Verilog netlist generated by SCUBA Diamond_3.1_Production (93) */
/* Module Version: 5.6 */
/* C:\lscc\diamond\3.1_x64\ispfpga\bin\nt64\scuba.exe -w -n DataFiFoInbetriebnahme -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 1024 -width 16 -rwidth 8 -no_enable -pe 639 -pf 640  */
/* Sat Apr 12 11:04:25 2014 */


`timescale 1 ns / 1 ps
module DataFiFoInbetriebnahme (Data, WrClock, RdClock, WrEn, RdEn, Reset, 
    RPReset, Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    // synopsys translate_off
    defparam DataFiFoInbetriebnahme_0_1.FULLPOINTER1 = 14'b01111111110001 ;
    defparam DataFiFoInbetriebnahme_0_1.FULLPOINTER = 14'b01111111111001 ;
    defparam DataFiFoInbetriebnahme_0_1.AFPOINTER1 = 14'b01001111110001 ;
    defparam DataFiFoInbetriebnahme_0_1.AFPOINTER = 14'b01001111111001 ;
    defparam DataFiFoInbetriebnahme_0_1.AEPOINTER1 = 14'b00101000000011 ;
    defparam DataFiFoInbetriebnahme_0_1.AEPOINTER = 14'b00100111111111 ;
    defparam DataFiFoInbetriebnahme_0_1.RESETMODE = "ASYNC" ;
    defparam DataFiFoInbetriebnahme_0_1.REGMODE = "NOREG" ;
    defparam DataFiFoInbetriebnahme_0_1.CSDECODE_R =  2'b11 ;
    defparam DataFiFoInbetriebnahme_0_1.CSDECODE_W =  2'b11 ;
    defparam DataFiFoInbetriebnahme_0_1.DATA_WIDTH_R = 4 ;
    defparam DataFiFoInbetriebnahme_0_1.DATA_WIDTH_W = 9 ;
    // synopsys translate_on
    FIFO8KA DataFiFoInbetriebnahme_0_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[8]), .DI5(Data[9]), .DI6(Data[10]), .DI7(Data[11]), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .DI18(scuba_vlo), .DI19(scuba_vlo), 
        .DI20(scuba_vlo), .DI21(scuba_vlo), .DI22(scuba_vlo), .DI23(scuba_vlo), 
        .DI24(scuba_vlo), .DI25(scuba_vlo), .DI26(scuba_vlo), .DI27(scuba_vlo), 
        .DI28(scuba_vlo), .DI29(scuba_vlo), .DI30(scuba_vlo), .DI31(scuba_vlo), 
        .DI32(scuba_vlo), .DI33(scuba_vlo), .DI34(scuba_vlo), .DI35(scuba_vlo), 
        .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(Q[2]), .DO3(Q[3]), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), 
        .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), 
        .DO33(), .DO34(), .DO35(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), 
        .FF(Full_int))
             /* synthesis FULLPOINTER1="0b01111111110001" */
             /* synthesis FULLPOINTER="0b01111111111001" */
             /* synthesis AFPOINTER1="0b01001111110001" */
             /* synthesis AFPOINTER="0b01001111111001" */
             /* synthesis AEPOINTER1="0b00101000000011" */
             /* synthesis AEPOINTER="0b00100111111111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="9" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam DataFiFoInbetriebnahme_1_0.FULLPOINTER1 = 14'b00000000000000 ;
    defparam DataFiFoInbetriebnahme_1_0.FULLPOINTER = 14'b11111111111111 ;
    defparam DataFiFoInbetriebnahme_1_0.AFPOINTER1 = 14'b00000000000000 ;
    defparam DataFiFoInbetriebnahme_1_0.AFPOINTER = 14'b11111111111111 ;
    defparam DataFiFoInbetriebnahme_1_0.AEPOINTER1 = 14'b00000000000000 ;
    defparam DataFiFoInbetriebnahme_1_0.AEPOINTER = 14'b11111111111111 ;
    defparam DataFiFoInbetriebnahme_1_0.RESETMODE = "ASYNC" ;
    defparam DataFiFoInbetriebnahme_1_0.REGMODE = "NOREG" ;
    defparam DataFiFoInbetriebnahme_1_0.CSDECODE_R =  2'b11 ;
    defparam DataFiFoInbetriebnahme_1_0.CSDECODE_W =  2'b11 ;
    defparam DataFiFoInbetriebnahme_1_0.DATA_WIDTH_R = 4 ;
    defparam DataFiFoInbetriebnahme_1_0.DATA_WIDTH_W = 9 ;
    // synopsys translate_on
    FIFO8KA DataFiFoInbetriebnahme_1_0 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .DI4(Data[12]), .DI5(Data[13]), .DI6(Data[14]), .DI7(Data[15]), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .DI18(scuba_vlo), .DI19(scuba_vlo), 
        .DI20(scuba_vlo), .DI21(scuba_vlo), .DI22(scuba_vlo), .DI23(scuba_vlo), 
        .DI24(scuba_vlo), .DI25(scuba_vlo), .DI26(scuba_vlo), .DI27(scuba_vlo), 
        .DI28(scuba_vlo), .DI29(scuba_vlo), .DI30(scuba_vlo), .DI31(scuba_vlo), 
        .DI32(scuba_vlo), .DI33(scuba_vlo), .DI34(scuba_vlo), .DI35(scuba_vlo), 
        .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[4]), .DO1(Q[5]), 
        .DO2(Q[6]), .DO3(Q[7]), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), 
        .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), 
        .DO33(), .DO34(), .DO35(), .EF(), .AEF(), .AFF(), .FF())
             /* synthesis FULLPOINTER1="0b00000000000000" */
             /* synthesis FULLPOINTER="0b11111111111111" */
             /* synthesis AFPOINTER1="0b00000000000000" */
             /* synthesis AFPOINTER="0b11111111111111" */
             /* synthesis AEPOINTER1="0b00000000000000" */
             /* synthesis AEPOINTER="0b11111111111111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="4" */
             /* synthesis DATA_WIDTH_W="9" */;

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute DataFiFoInbetriebnahme_0_1 FULLPOINTER1 0b01111111110001
    // exemplar attribute DataFiFoInbetriebnahme_0_1 FULLPOINTER 0b01111111111001
    // exemplar attribute DataFiFoInbetriebnahme_0_1 AFPOINTER1 0b01001111110001
    // exemplar attribute DataFiFoInbetriebnahme_0_1 AFPOINTER 0b01001111111001
    // exemplar attribute DataFiFoInbetriebnahme_0_1 AEPOINTER1 0b00101000000011
    // exemplar attribute DataFiFoInbetriebnahme_0_1 AEPOINTER 0b00100111111111
    // exemplar attribute DataFiFoInbetriebnahme_0_1 RESETMODE ASYNC
    // exemplar attribute DataFiFoInbetriebnahme_0_1 REGMODE NOREG
    // exemplar attribute DataFiFoInbetriebnahme_0_1 CSDECODE_R 0b11
    // exemplar attribute DataFiFoInbetriebnahme_0_1 CSDECODE_W 0b11
    // exemplar attribute DataFiFoInbetriebnahme_0_1 DATA_WIDTH_R 4
    // exemplar attribute DataFiFoInbetriebnahme_0_1 DATA_WIDTH_W 9
    // exemplar attribute DataFiFoInbetriebnahme_1_0 FULLPOINTER1 0b00000000000000
    // exemplar attribute DataFiFoInbetriebnahme_1_0 FULLPOINTER 0b11111111111111
    // exemplar attribute DataFiFoInbetriebnahme_1_0 AFPOINTER1 0b00000000000000
    // exemplar attribute DataFiFoInbetriebnahme_1_0 AFPOINTER 0b11111111111111
    // exemplar attribute DataFiFoInbetriebnahme_1_0 AEPOINTER1 0b00000000000000
    // exemplar attribute DataFiFoInbetriebnahme_1_0 AEPOINTER 0b11111111111111
    // exemplar attribute DataFiFoInbetriebnahme_1_0 RESETMODE ASYNC
    // exemplar attribute DataFiFoInbetriebnahme_1_0 REGMODE NOREG
    // exemplar attribute DataFiFoInbetriebnahme_1_0 CSDECODE_R 0b11
    // exemplar attribute DataFiFoInbetriebnahme_1_0 CSDECODE_W 0b11
    // exemplar attribute DataFiFoInbetriebnahme_1_0 DATA_WIDTH_R 4
    // exemplar attribute DataFiFoInbetriebnahme_1_0 DATA_WIDTH_W 9
    // exemplar end

endmodule
