/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.5 */
/* C:\lscc\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n DataFifo -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 1024 -width 8 -rwidth 8 -no_enable -pe 511 -pf 600 -e  */
/* Mon Jul 29 13:26:31 2013 */


`timescale 1 ns / 1 ps
module DataFifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam DataFifo_0_0.FULLPOINTER1 = 14'b01111111110001 ;
    defparam DataFifo_0_0.FULLPOINTER = 14'b01111111111001 ;
    defparam DataFifo_0_0.AFPOINTER1 = 14'b01001010110001 ;
    defparam DataFifo_0_0.AFPOINTER = 14'b01001010111001 ;
    defparam DataFifo_0_0.AEPOINTER1 = 14'b01000000000111 ;
    defparam DataFifo_0_0.AEPOINTER = 14'b00111111111111 ;
    defparam DataFifo_0_0.RESETMODE = "ASYNC" ;
    defparam DataFifo_0_0.REGMODE = "NOREG" ;
    defparam DataFifo_0_0.CSDECODE_R =  2'b11 ;
    defparam DataFifo_0_0.CSDECODE_W =  2'b11 ;
    defparam DataFifo_0_0.DATA_WIDTH_R = 9 ;
    defparam DataFifo_0_0.DATA_WIDTH_W = 9 ;
    // synopsys translate_on
    FIFO8KA DataFifo_0_0 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), .DI8(scuba_vlo), 
        .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), .DI12(scuba_vlo), 
        .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), .DI16(scuba_vlo), 
        .DI17(scuba_vlo), .DI18(scuba_vlo), .DI19(scuba_vlo), .DI20(scuba_vlo), 
        .DI21(scuba_vlo), .DI22(scuba_vlo), .DI23(scuba_vlo), .DI24(scuba_vlo), 
        .DI25(scuba_vlo), .DI26(scuba_vlo), .DI27(scuba_vlo), .DI28(scuba_vlo), 
        .DI29(scuba_vlo), .DI30(scuba_vlo), .DI31(scuba_vlo), .DI32(scuba_vlo), 
        .DI33(scuba_vlo), .DI34(scuba_vlo), .DI35(scuba_vlo), .FULLI(Full_int), 
        .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), .CSR0(scuba_vhi), 
        .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), .DO2(Q[2]), 
        .DO3(Q[3]), .DO4(Q[4]), .DO5(Q[5]), .DO6(Q[6]), .DO7(Q[7]), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), 
        .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), 
        .DO33(), .DO34(), .DO35(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), 
        .FF(Full_int))
             /* synthesis FULLPOINTER1="0b01111111110001" */
             /* synthesis FULLPOINTER="0b01111111111001" */
             /* synthesis AFPOINTER1="0b01001010110001" */
             /* synthesis AFPOINTER="0b01001010111001" */
             /* synthesis AEPOINTER1="0b01000000000111" */
             /* synthesis AEPOINTER="0b00111111111111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="9" */
             /* synthesis DATA_WIDTH_W="9" */;

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute DataFifo_0_0 FULLPOINTER1 0b01111111110001
    // exemplar attribute DataFifo_0_0 FULLPOINTER 0b01111111111001
    // exemplar attribute DataFifo_0_0 AFPOINTER1 0b01001010110001
    // exemplar attribute DataFifo_0_0 AFPOINTER 0b01001010111001
    // exemplar attribute DataFifo_0_0 AEPOINTER1 0b01000000000111
    // exemplar attribute DataFifo_0_0 AEPOINTER 0b00111111111111
    // exemplar attribute DataFifo_0_0 RESETMODE ASYNC
    // exemplar attribute DataFifo_0_0 REGMODE NOREG
    // exemplar attribute DataFifo_0_0 CSDECODE_R 0b11
    // exemplar attribute DataFifo_0_0 CSDECODE_W 0b11
    // exemplar attribute DataFifo_0_0 DATA_WIDTH_R 9
    // exemplar attribute DataFifo_0_0 DATA_WIDTH_W 9
    // exemplar end

endmodule
