/* Verilog module instantiation template generated by SCUBA Diamond_3.1_Production (93) */
/* Module Version: 5.6 */
/* Sat Apr 12 11:04:25 2014 */

/* parameterized module instance */
DataFiFoInbetriebnahme __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), 
    .RdEn( ), .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), 
    .AlmostEmpty( ), .AlmostFull( ));
