/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 5.5 */
/* C:\lscc\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n OutBuffer -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 256 -width 64 -rwidth 64 -no_enable -pe 20 -pf 180 -e  */
/* Sat Jan 18 16:27:54 2014 */


`timescale 1 ns / 1 ps
module OutBuffer (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [63:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [63:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    // synopsys translate_off
    defparam OutBuffer_0_1.FULLPOINTER1 = 14'b01111111000001 ;
    defparam OutBuffer_0_1.FULLPOINTER = 14'b01111111100001 ;
    defparam OutBuffer_0_1.AFPOINTER1 = 14'b01011001000001 ;
    defparam OutBuffer_0_1.AFPOINTER = 14'b01011001100001 ;
    defparam OutBuffer_0_1.AEPOINTER1 = 14'b00001010111111 ;
    defparam OutBuffer_0_1.AEPOINTER = 14'b00001010011111 ;
    defparam OutBuffer_0_1.RESETMODE = "ASYNC" ;
    defparam OutBuffer_0_1.REGMODE = "NOREG" ;
    defparam OutBuffer_0_1.CSDECODE_R =  2'b11 ;
    defparam OutBuffer_0_1.CSDECODE_W =  2'b11 ;
    defparam OutBuffer_0_1.DATA_WIDTH_R = 36 ;
    defparam OutBuffer_0_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    FIFO8KA OutBuffer_0_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(Data[16]), .DI17(Data[17]), .DI18(Data[18]), .DI19(Data[19]), 
        .DI20(Data[20]), .DI21(Data[21]), .DI22(Data[22]), .DI23(Data[23]), 
        .DI24(Data[24]), .DI25(Data[25]), .DI26(Data[26]), .DI27(Data[27]), 
        .DI28(Data[28]), .DI29(Data[29]), .DI30(Data[30]), .DI31(Data[31]), 
        .DI32(Data[32]), .DI33(Data[33]), .DI34(Data[34]), .DI35(Data[35]), 
        .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[18]), .DO1(Q[19]), 
        .DO2(Q[20]), .DO3(Q[21]), .DO4(Q[22]), .DO5(Q[23]), .DO6(Q[24]), 
        .DO7(Q[25]), .DO8(Q[26]), .DO9(Q[27]), .DO10(Q[28]), .DO11(Q[29]), 
        .DO12(Q[30]), .DO13(Q[31]), .DO14(Q[32]), .DO15(Q[33]), .DO16(Q[34]), 
        .DO17(Q[35]), .DO18(Q[0]), .DO19(Q[1]), .DO20(Q[2]), .DO21(Q[3]), 
        .DO22(Q[4]), .DO23(Q[5]), .DO24(Q[6]), .DO25(Q[7]), .DO26(Q[8]), 
        .DO27(Q[9]), .DO28(Q[10]), .DO29(Q[11]), .DO30(Q[12]), .DO31(Q[13]), 
        .DO32(Q[14]), .DO33(Q[15]), .DO34(Q[16]), .DO35(Q[17]), .EF(Empty_int), 
        .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int))
             /* synthesis FULLPOINTER1="0b01111111000001" */
             /* synthesis FULLPOINTER="0b01111111100001" */
             /* synthesis AFPOINTER1="0b01011001000001" */
             /* synthesis AFPOINTER="0b01011001100001" */
             /* synthesis AEPOINTER1="0b00001010111111" */
             /* synthesis AEPOINTER="0b00001010011111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam OutBuffer_1_0.FULLPOINTER1 = 14'b00000000000000 ;
    defparam OutBuffer_1_0.FULLPOINTER = 14'b11111111111111 ;
    defparam OutBuffer_1_0.AFPOINTER1 = 14'b00000000000000 ;
    defparam OutBuffer_1_0.AFPOINTER = 14'b11111111111111 ;
    defparam OutBuffer_1_0.AEPOINTER1 = 14'b00000000000000 ;
    defparam OutBuffer_1_0.AEPOINTER = 14'b11111111111111 ;
    defparam OutBuffer_1_0.RESETMODE = "ASYNC" ;
    defparam OutBuffer_1_0.REGMODE = "NOREG" ;
    defparam OutBuffer_1_0.CSDECODE_R =  2'b11 ;
    defparam OutBuffer_1_0.CSDECODE_W =  2'b11 ;
    defparam OutBuffer_1_0.DATA_WIDTH_R = 36 ;
    defparam OutBuffer_1_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    FIFO8KA OutBuffer_1_0 (.DI0(Data[36]), .DI1(Data[37]), .DI2(Data[38]), 
        .DI3(Data[39]), .DI4(Data[40]), .DI5(Data[41]), .DI6(Data[42]), 
        .DI7(Data[43]), .DI8(Data[44]), .DI9(Data[45]), .DI10(Data[46]), 
        .DI11(Data[47]), .DI12(Data[48]), .DI13(Data[49]), .DI14(Data[50]), 
        .DI15(Data[51]), .DI16(Data[52]), .DI17(Data[53]), .DI18(Data[54]), 
        .DI19(Data[55]), .DI20(Data[56]), .DI21(Data[57]), .DI22(Data[58]), 
        .DI23(Data[59]), .DI24(Data[60]), .DI25(Data[61]), .DI26(Data[62]), 
        .DI27(Data[63]), .DI28(scuba_vlo), .DI29(scuba_vlo), .DI30(scuba_vlo), 
        .DI31(scuba_vlo), .DI32(scuba_vlo), .DI33(scuba_vlo), .DI34(scuba_vlo), 
        .DI35(scuba_vlo), .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .EMPTYI(Empty_int), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), 
        .RE(RdEn), .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), 
        .DO0(Q[54]), .DO1(Q[55]), .DO2(Q[56]), .DO3(Q[57]), .DO4(Q[58]), 
        .DO5(Q[59]), .DO6(Q[60]), .DO7(Q[61]), .DO8(Q[62]), .DO9(Q[63]), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .DO18(Q[36]), .DO19(Q[37]), .DO20(Q[38]), .DO21(Q[39]), .DO22(Q[40]), 
        .DO23(Q[41]), .DO24(Q[42]), .DO25(Q[43]), .DO26(Q[44]), .DO27(Q[45]), 
        .DO28(Q[46]), .DO29(Q[47]), .DO30(Q[48]), .DO31(Q[49]), .DO32(Q[50]), 
        .DO33(Q[51]), .DO34(Q[52]), .DO35(Q[53]), .EF(), .AEF(), .AFF(), 
        .FF())
             /* synthesis FULLPOINTER1="0b00000000000000" */
             /* synthesis FULLPOINTER="0b11111111111111" */
             /* synthesis AFPOINTER1="0b00000000000000" */
             /* synthesis AFPOINTER="0b11111111111111" */
             /* synthesis AEPOINTER1="0b00000000000000" */
             /* synthesis AEPOINTER="0b11111111111111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute OutBuffer_0_1 FULLPOINTER1 0b01111111000001
    // exemplar attribute OutBuffer_0_1 FULLPOINTER 0b01111111100001
    // exemplar attribute OutBuffer_0_1 AFPOINTER1 0b01011001000001
    // exemplar attribute OutBuffer_0_1 AFPOINTER 0b01011001100001
    // exemplar attribute OutBuffer_0_1 AEPOINTER1 0b00001010111111
    // exemplar attribute OutBuffer_0_1 AEPOINTER 0b00001010011111
    // exemplar attribute OutBuffer_0_1 RESETMODE ASYNC
    // exemplar attribute OutBuffer_0_1 REGMODE NOREG
    // exemplar attribute OutBuffer_0_1 CSDECODE_R 0b11
    // exemplar attribute OutBuffer_0_1 CSDECODE_W 0b11
    // exemplar attribute OutBuffer_0_1 DATA_WIDTH_R 36
    // exemplar attribute OutBuffer_0_1 DATA_WIDTH_W 36
    // exemplar attribute OutBuffer_1_0 FULLPOINTER1 0b00000000000000
    // exemplar attribute OutBuffer_1_0 FULLPOINTER 0b11111111111111
    // exemplar attribute OutBuffer_1_0 AFPOINTER1 0b00000000000000
    // exemplar attribute OutBuffer_1_0 AFPOINTER 0b11111111111111
    // exemplar attribute OutBuffer_1_0 AEPOINTER1 0b00000000000000
    // exemplar attribute OutBuffer_1_0 AEPOINTER 0b11111111111111
    // exemplar attribute OutBuffer_1_0 RESETMODE ASYNC
    // exemplar attribute OutBuffer_1_0 REGMODE NOREG
    // exemplar attribute OutBuffer_1_0 CSDECODE_R 0b11
    // exemplar attribute OutBuffer_1_0 CSDECODE_W 0b11
    // exemplar attribute OutBuffer_1_0 DATA_WIDTH_R 36
    // exemplar attribute OutBuffer_1_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
