/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 5.7 */
/* C:\lscc\diamond\3.4_x64\ispfpga\bin\nt64\scuba.exe -w -n FIFO_EBR_1x -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 512 -width 16 -rwidth 16 -no_enable -pe 64 -pf 320  */
/* Mon Feb 23 01:09:38 2015 */


`timescale 1 ns / 1 ps
module FIFO_EBR_1x (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [15:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam FIFO_EBR_1x_0_0.FULLPOINTER1 = 14'b01111111100001 ;
    defparam FIFO_EBR_1x_0_0.FULLPOINTER = 14'b01111111110001 ;
    defparam FIFO_EBR_1x_0_0.AFPOINTER1 = 14'b01001111100001 ;
    defparam FIFO_EBR_1x_0_0.AFPOINTER = 14'b01001111110001 ;
    defparam FIFO_EBR_1x_0_0.AEPOINTER1 = 14'b00010000011111 ;
    defparam FIFO_EBR_1x_0_0.AEPOINTER = 14'b00010000001111 ;
    defparam FIFO_EBR_1x_0_0.RESETMODE = "ASYNC" ;
    defparam FIFO_EBR_1x_0_0.REGMODE = "NOREG" ;
    defparam FIFO_EBR_1x_0_0.CSDECODE_R =  2'b11 ;
    defparam FIFO_EBR_1x_0_0.CSDECODE_W =  2'b11 ;
    defparam FIFO_EBR_1x_0_0.DATA_WIDTH_R = 18 ;
    defparam FIFO_EBR_1x_0_0.DATA_WIDTH_W = 18 ;
    // synopsys translate_on
    FIFO8KA FIFO_EBR_1x_0_0 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .DI18(scuba_vlo), .DI19(scuba_vlo), 
        .DI20(scuba_vlo), .DI21(scuba_vlo), .DI22(scuba_vlo), .DI23(scuba_vlo), 
        .DI24(scuba_vlo), .DI25(scuba_vlo), .DI26(scuba_vlo), .DI27(scuba_vlo), 
        .DI28(scuba_vlo), .DI29(scuba_vlo), .DI30(scuba_vlo), .DI31(scuba_vlo), 
        .DI32(scuba_vlo), .DI33(scuba_vlo), .DI34(scuba_vlo), .DI35(scuba_vlo), 
        .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(Q[2]), .DO3(Q[3]), .DO4(Q[4]), .DO5(Q[5]), .DO6(Q[6]), .DO7(Q[7]), 
        .DO8(Q[8]), .DO9(Q[9]), .DO10(Q[10]), .DO11(Q[11]), .DO12(Q[12]), 
        .DO13(Q[13]), .DO14(Q[14]), .DO15(Q[15]), .DO16(), .DO17(), .DO18(), 
        .DO19(), .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), 
        .DO27(), .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), 
        .DO35(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int))
             /* synthesis FULLPOINTER1="0b01111111100001" */
             /* synthesis FULLPOINTER="0b01111111110001" */
             /* synthesis AFPOINTER1="0b01001111100001" */
             /* synthesis AFPOINTER="0b01001111110001" */
             /* synthesis AEPOINTER1="0b00010000011111" */
             /* synthesis AEPOINTER="0b00010000001111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="18" */
             /* synthesis DATA_WIDTH_W="18" */;

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute FIFO_EBR_1x_0_0 FULLPOINTER1 0b01111111100001
    // exemplar attribute FIFO_EBR_1x_0_0 FULLPOINTER 0b01111111110001
    // exemplar attribute FIFO_EBR_1x_0_0 AFPOINTER1 0b01001111100001
    // exemplar attribute FIFO_EBR_1x_0_0 AFPOINTER 0b01001111110001
    // exemplar attribute FIFO_EBR_1x_0_0 AEPOINTER1 0b00010000011111
    // exemplar attribute FIFO_EBR_1x_0_0 AEPOINTER 0b00010000001111
    // exemplar attribute FIFO_EBR_1x_0_0 RESETMODE ASYNC
    // exemplar attribute FIFO_EBR_1x_0_0 REGMODE NOREG
    // exemplar attribute FIFO_EBR_1x_0_0 CSDECODE_R 0b11
    // exemplar attribute FIFO_EBR_1x_0_0 CSDECODE_W 0b11
    // exemplar attribute FIFO_EBR_1x_0_0 DATA_WIDTH_R 18
    // exemplar attribute FIFO_EBR_1x_0_0 DATA_WIDTH_W 18
    // exemplar end

endmodule
