/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 5.7 */
/* Sun Mar 08 13:40:19 2015 */

/* parameterized module instance */
FIFO_EBR_2x __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
