/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 5.7 */
/* C:\lscc\diamond\3.4_x64\ispfpga\bin\nt64\scuba.exe -w -n FIFO_EBR_2x -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type ebfifo -depth 256 -width 64 -rwidth 16 -no_enable -pe 200 -pf 240  */
/* Sun Mar 08 13:40:19 2015 */


`timescale 1 ns / 1 ps
module FIFO_EBR_2x (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [63:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [15:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    // synopsys translate_off
    defparam FIFO_EBR_2x_0_1.FULLPOINTER1 = 14'b01111111000001 ;
    defparam FIFO_EBR_2x_0_1.FULLPOINTER = 14'b01111111100001 ;
    defparam FIFO_EBR_2x_0_1.AFPOINTER1 = 14'b01110111000001 ;
    defparam FIFO_EBR_2x_0_1.AFPOINTER = 14'b01110111100001 ;
    defparam FIFO_EBR_2x_0_1.AEPOINTER1 = 14'b00011001001111 ;
    defparam FIFO_EBR_2x_0_1.AEPOINTER = 14'b00011001000111 ;
    defparam FIFO_EBR_2x_0_1.RESETMODE = "ASYNC" ;
    defparam FIFO_EBR_2x_0_1.REGMODE = "NOREG" ;
    defparam FIFO_EBR_2x_0_1.CSDECODE_R =  2'b11 ;
    defparam FIFO_EBR_2x_0_1.CSDECODE_W =  2'b11 ;
    defparam FIFO_EBR_2x_0_1.DATA_WIDTH_R = 9 ;
    defparam FIFO_EBR_2x_0_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    FIFO8KA FIFO_EBR_2x_0_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), .DI7(Data[7]), 
        .DI8(Data[8]), .DI9(Data[16]), .DI10(Data[17]), .DI11(Data[18]), 
        .DI12(Data[19]), .DI13(Data[20]), .DI14(Data[21]), .DI15(Data[22]), 
        .DI16(Data[23]), .DI17(Data[24]), .DI18(Data[32]), .DI19(Data[33]), 
        .DI20(Data[34]), .DI21(Data[35]), .DI22(Data[36]), .DI23(Data[37]), 
        .DI24(Data[38]), .DI25(Data[39]), .DI26(Data[40]), .DI27(Data[48]), 
        .DI28(Data[49]), .DI29(Data[50]), .DI30(Data[51]), .DI31(Data[52]), 
        .DI32(Data[53]), .DI33(Data[54]), .DI34(Data[55]), .DI35(Data[56]), 
        .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), .EMPTYI(Empty_int), 
        .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), .RE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(Q[2]), .DO3(Q[3]), .DO4(Q[4]), .DO5(Q[5]), .DO6(Q[6]), .DO7(Q[7]), 
        .DO8(Q[8]), .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), 
        .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), .DO20(), .DO21(), .DO22(), 
        .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), .DO28(), .DO29(), .DO30(), 
        .DO31(), .DO32(), .DO33(), .DO34(), .DO35(), .EF(Empty_int), .AEF(AlmostEmpty), 
        .AFF(AlmostFull), .FF(Full_int))
             /* synthesis FULLPOINTER1="0b01111111000001" */
             /* synthesis FULLPOINTER="0b01111111100001" */
             /* synthesis AFPOINTER1="0b01110111000001" */
             /* synthesis AFPOINTER="0b01110111100001" */
             /* synthesis AEPOINTER1="0b00011001001111" */
             /* synthesis AEPOINTER="0b00011001000111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="9" */
             /* synthesis DATA_WIDTH_W="36" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam FIFO_EBR_2x_1_0.FULLPOINTER1 = 14'b00000000000000 ;
    defparam FIFO_EBR_2x_1_0.FULLPOINTER = 14'b11111111111111 ;
    defparam FIFO_EBR_2x_1_0.AFPOINTER1 = 14'b00000000000000 ;
    defparam FIFO_EBR_2x_1_0.AFPOINTER = 14'b11111111111111 ;
    defparam FIFO_EBR_2x_1_0.AEPOINTER1 = 14'b00000000000000 ;
    defparam FIFO_EBR_2x_1_0.AEPOINTER = 14'b11111111111111 ;
    defparam FIFO_EBR_2x_1_0.RESETMODE = "ASYNC" ;
    defparam FIFO_EBR_2x_1_0.REGMODE = "NOREG" ;
    defparam FIFO_EBR_2x_1_0.CSDECODE_R =  2'b11 ;
    defparam FIFO_EBR_2x_1_0.CSDECODE_W =  2'b11 ;
    defparam FIFO_EBR_2x_1_0.DATA_WIDTH_R = 9 ;
    defparam FIFO_EBR_2x_1_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    FIFO8KA FIFO_EBR_2x_1_0 (.DI0(Data[9]), .DI1(Data[10]), .DI2(Data[11]), 
        .DI3(Data[12]), .DI4(Data[13]), .DI5(Data[14]), .DI6(Data[15]), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(Data[25]), .DI10(Data[26]), 
        .DI11(Data[27]), .DI12(Data[28]), .DI13(Data[29]), .DI14(Data[30]), 
        .DI15(Data[31]), .DI16(scuba_vlo), .DI17(scuba_vlo), .DI18(Data[41]), 
        .DI19(Data[42]), .DI20(Data[43]), .DI21(Data[44]), .DI22(Data[45]), 
        .DI23(Data[46]), .DI24(Data[47]), .DI25(scuba_vlo), .DI26(scuba_vlo), 
        .DI27(Data[57]), .DI28(Data[58]), .DI29(Data[59]), .DI30(Data[60]), 
        .DI31(Data[61]), .DI32(Data[62]), .DI33(Data[63]), .DI34(scuba_vlo), 
        .DI35(scuba_vlo), .FULLI(Full_int), .CSW0(scuba_vhi), .CSW1(scuba_vhi), 
        .EMPTYI(Empty_int), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .WE(WrEn), 
        .RE(RdEn), .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), 
        .DO0(Q[9]), .DO1(Q[10]), .DO2(Q[11]), .DO3(Q[12]), .DO4(Q[13]), 
        .DO5(Q[14]), .DO6(Q[15]), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .DO18(), .DO19(), 
        .DO20(), .DO21(), .DO22(), .DO23(), .DO24(), .DO25(), .DO26(), .DO27(), 
        .DO28(), .DO29(), .DO30(), .DO31(), .DO32(), .DO33(), .DO34(), .DO35(), 
        .EF(), .AEF(), .AFF(), .FF())
             /* synthesis FULLPOINTER1="0b00000000000000" */
             /* synthesis FULLPOINTER="0b11111111111111" */
             /* synthesis AFPOINTER1="0b00000000000000" */
             /* synthesis AFPOINTER="0b11111111111111" */
             /* synthesis AEPOINTER1="0b00000000000000" */
             /* synthesis AEPOINTER="0b11111111111111" */
             /* synthesis RESETMODE="ASYNC" */
             /* synthesis REGMODE="NOREG" */
             /* synthesis CSDECODE_R="0b11" */
             /* synthesis CSDECODE_W="0b11" */
             /* synthesis DATA_WIDTH_R="9" */
             /* synthesis DATA_WIDTH_W="36" */;

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute FIFO_EBR_2x_0_1 FULLPOINTER1 0b01111111000001
    // exemplar attribute FIFO_EBR_2x_0_1 FULLPOINTER 0b01111111100001
    // exemplar attribute FIFO_EBR_2x_0_1 AFPOINTER1 0b01110111000001
    // exemplar attribute FIFO_EBR_2x_0_1 AFPOINTER 0b01110111100001
    // exemplar attribute FIFO_EBR_2x_0_1 AEPOINTER1 0b00011001001111
    // exemplar attribute FIFO_EBR_2x_0_1 AEPOINTER 0b00011001000111
    // exemplar attribute FIFO_EBR_2x_0_1 RESETMODE ASYNC
    // exemplar attribute FIFO_EBR_2x_0_1 REGMODE NOREG
    // exemplar attribute FIFO_EBR_2x_0_1 CSDECODE_R 0b11
    // exemplar attribute FIFO_EBR_2x_0_1 CSDECODE_W 0b11
    // exemplar attribute FIFO_EBR_2x_0_1 DATA_WIDTH_R 9
    // exemplar attribute FIFO_EBR_2x_0_1 DATA_WIDTH_W 36
    // exemplar attribute FIFO_EBR_2x_1_0 FULLPOINTER1 0b00000000000000
    // exemplar attribute FIFO_EBR_2x_1_0 FULLPOINTER 0b11111111111111
    // exemplar attribute FIFO_EBR_2x_1_0 AFPOINTER1 0b00000000000000
    // exemplar attribute FIFO_EBR_2x_1_0 AFPOINTER 0b11111111111111
    // exemplar attribute FIFO_EBR_2x_1_0 AEPOINTER1 0b00000000000000
    // exemplar attribute FIFO_EBR_2x_1_0 AEPOINTER 0b11111111111111
    // exemplar attribute FIFO_EBR_2x_1_0 RESETMODE ASYNC
    // exemplar attribute FIFO_EBR_2x_1_0 REGMODE NOREG
    // exemplar attribute FIFO_EBR_2x_1_0 CSDECODE_R 0b11
    // exemplar attribute FIFO_EBR_2x_1_0 CSDECODE_W 0b11
    // exemplar attribute FIFO_EBR_2x_1_0 DATA_WIDTH_R 9
    // exemplar attribute FIFO_EBR_2x_1_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
