/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 3.4 */
/* Thu Mar 05 11:33:44 2015 */

/* parameterized module instance */
add32 __ (.DataA( ), .DataB( ), .Result( ));
