/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 4.8 */
/* C:\lscc\diamond\3.4_x64\ispfpga\bin\nt64\scuba.exe -w -n multiply -lang verilog -synth synplify -bus_exp 7 -bb -arch mj5g00 -type dspmult -simple_portname -pfu_mult -widtha 8 -widthb 14 -widthp 22 -signed -PL_stages 1 -input_reg -output_reg -clk0 -ce0 -rst0  */
/* Thu Mar 05 11:22:52 2015 */


`timescale 1 ns / 1 ps
module multiply (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [7:0] DataA;
    input wire [13:0] DataB;
    output wire [21:0] Result;

    wire rego_o_0;
    wire rego_o_1;
    wire rego_o_2;
    wire rego_o_3;
    wire f_multiply_0_pp_0_0;
    wire multiply_0_pp_0_0;
    wire f_multiply_0_pp_0_1;
    wire f_s_multiply_0_0_2;
    wire f_s_multiply_0_0_3;
    wire multiply_0_pp_2_4;
    wire s_multiply_0_0_2;
    wire s_multiply_0_0_3;
    wire multiply_0_pp_1_2;
    wire s_multiply_0_0_4;
    wire s_multiply_0_0_5;
    wire co_multiply_0_0_1;
    wire s_multiply_0_0_6;
    wire s_multiply_0_0_7;
    wire co_multiply_0_0_2;
    wire s_multiply_0_0_8;
    wire s_multiply_0_0_9;
    wire co_multiply_0_0_3;
    wire s_multiply_0_0_10;
    wire s_multiply_0_0_11;
    wire co_multiply_0_0_4;
    wire s_multiply_0_0_12;
    wire s_multiply_0_0_13;
    wire co_multiply_0_0_5;
    wire s_multiply_0_0_14;
    wire s_multiply_0_0_15;
    wire co_multiply_0_0_6;
    wire multiply_0_pp_0_15;
    wire s_multiply_0_0_16;
    wire s_multiply_0_0_17;
    wire co_multiply_0_0_7;
    wire multiply_0_pp_1_17;
    wire s_multiply_0_0_18;
    wire co_multiply_0_0_8;
    wire s_multiply_0_1_6;
    wire s_multiply_0_1_7;
    wire multiply_0_pp_3_6;
    wire s_multiply_0_1_8;
    wire s_multiply_0_1_9;
    wire co_multiply_0_1_1;
    wire s_multiply_0_1_10;
    wire s_multiply_0_1_11;
    wire co_multiply_0_1_2;
    wire s_multiply_0_1_12;
    wire s_multiply_0_1_13;
    wire co_multiply_0_1_3;
    wire s_multiply_0_1_14;
    wire s_multiply_0_1_15;
    wire co_multiply_0_1_4;
    wire s_multiply_0_1_16;
    wire s_multiply_0_1_17;
    wire co_multiply_0_1_5;
    wire s_multiply_0_1_18;
    wire s_multiply_0_1_19;
    wire co_multiply_0_1_6;
    wire multiply_0_pp_2_19;
    wire s_multiply_0_1_20;
    wire s_multiply_0_1_21;
    wire co_multiply_0_1_8;
    wire co_multiply_0_1_7;
    wire multiply_0_pp_3_21;
    wire rego_o_4;
    wire rego_o_5;
    wire f_multiply_0_pp_2_4;
    wire f_multiply_0_pp_2_5;
    wire f_s_multiply_0_0_4;
    wire f_s_multiply_0_0_5;
    wire rego_o_6;
    wire rego_o_7;
    wire co_t_multiply_0_2_1;
    wire f_s_multiply_0_1_6;
    wire f_s_multiply_0_1_7;
    wire f_s_multiply_0_0_6;
    wire f_s_multiply_0_0_7;
    wire rego_o_8;
    wire rego_o_9;
    wire co_t_multiply_0_2_2;
    wire f_s_multiply_0_1_8;
    wire f_s_multiply_0_1_9;
    wire f_s_multiply_0_0_8;
    wire f_s_multiply_0_0_9;
    wire rego_o_10;
    wire rego_o_11;
    wire co_t_multiply_0_2_3;
    wire f_s_multiply_0_1_10;
    wire f_s_multiply_0_1_11;
    wire f_s_multiply_0_0_10;
    wire f_s_multiply_0_0_11;
    wire rego_o_12;
    wire rego_o_13;
    wire co_t_multiply_0_2_4;
    wire f_s_multiply_0_1_12;
    wire f_s_multiply_0_1_13;
    wire f_s_multiply_0_0_12;
    wire f_s_multiply_0_0_13;
    wire rego_o_14;
    wire rego_o_15;
    wire co_t_multiply_0_2_5;
    wire f_s_multiply_0_1_14;
    wire f_s_multiply_0_1_15;
    wire f_s_multiply_0_0_14;
    wire f_s_multiply_0_0_15;
    wire rego_o_16;
    wire rego_o_17;
    wire co_t_multiply_0_2_6;
    wire f_s_multiply_0_1_16;
    wire f_s_multiply_0_1_17;
    wire f_s_multiply_0_0_16;
    wire f_s_multiply_0_0_17;
    wire rego_o_18;
    wire rego_o_19;
    wire co_t_multiply_0_2_7;
    wire f_s_multiply_0_1_18;
    wire f_s_multiply_0_1_19;
    wire f_s_multiply_0_0_18;
    wire rego_o_20;
    wire rego_o_21;
    wire co_t_multiply_0_2_9;
    wire co_t_multiply_0_2_8;
    wire f_s_multiply_0_1_20;
    wire f_s_multiply_0_1_21;
    wire multiply_0_pp_0_2;
    wire multiply_0_pp_0_1;
    wire multiply_0_pp_0_4;
    wire multiply_0_pp_0_3;
    wire mco;
    wire multiply_0_pp_0_6;
    wire multiply_0_pp_0_5;
    wire mco_1;
    wire multiply_0_pp_0_8;
    wire multiply_0_pp_0_7;
    wire mco_2;
    wire multiply_0_pp_0_10;
    wire multiply_0_pp_0_9;
    wire mco_3;
    wire multiply_0_pp_0_12;
    wire multiply_0_pp_0_11;
    wire mco_4;
    wire mfco;
    wire multiply_0_pp_0_14;
    wire multiply_0_pp_0_13;
    wire mco_5;
    wire multiply_0_mult_0_6_n3;
    wire multiply_0_mult_0_6_n1;
    wire rega_a_0;
    wire rega_a_1;
    wire multiply_0_pp_1_4;
    wire multiply_0_pp_1_3;
    wire multiply_0_pp_1_6;
    wire multiply_0_pp_1_5;
    wire mco_6;
    wire multiply_0_pp_1_8;
    wire multiply_0_pp_1_7;
    wire mco_7;
    wire multiply_0_pp_1_10;
    wire multiply_0_pp_1_9;
    wire mco_8;
    wire multiply_0_pp_1_12;
    wire multiply_0_pp_1_11;
    wire mco_9;
    wire multiply_0_pp_1_14;
    wire multiply_0_pp_1_13;
    wire mco_10;
    wire mfco_1;
    wire multiply_0_pp_1_16;
    wire multiply_0_pp_1_15;
    wire mco_11;
    wire rega_a_2;
    wire multiply_0_mult_2_6_n1;
    wire multiply_0_mult_2_6_n2;
    wire rega_a_3;
    wire multiply_0_pp_2_6;
    wire multiply_0_pp_2_5;
    wire regb_b_0;
    wire multiply_0_pp_2_8;
    wire multiply_0_pp_2_7;
    wire mco_12;
    wire multiply_0_pp_2_10;
    wire multiply_0_pp_2_9;
    wire mco_13;
    wire multiply_0_pp_2_12;
    wire multiply_0_pp_2_11;
    wire mco_14;
    wire multiply_0_pp_2_14;
    wire multiply_0_pp_2_13;
    wire mco_15;
    wire multiply_0_pp_2_16;
    wire multiply_0_pp_2_15;
    wire mco_16;
    wire mfco_2;
    wire multiply_0_pp_2_18;
    wire multiply_0_pp_2_17;
    wire mco_17;
    wire rega_a_4;
    wire multiply_0_mult_4_6_n1;
    wire multiply_0_mult_4_6_n2;
    wire rega_a_5;
    wire multiply_0_pp_3_8;
    wire multiply_0_pp_3_7;
    wire regb_b_2;
    wire multiply_0_mult_6_0_n1;
    wire regb_b_1;
    wire multiply_0_mult_6_0_n0;
    wire multiply_0_pp_3_10;
    wire multiply_0_pp_3_9;
    wire mco_18;
    wire regb_b_4;
    wire multiply_0_mult_6_1_n1;
    wire regb_b_3;
    wire multiply_0_mult_6_1_n0;
    wire multiply_0_pp_3_12;
    wire multiply_0_pp_3_11;
    wire mco_19;
    wire regb_b_6;
    wire multiply_0_mult_6_2_n1;
    wire regb_b_5;
    wire multiply_0_mult_6_2_n0;
    wire multiply_0_pp_3_14;
    wire multiply_0_pp_3_13;
    wire mco_20;
    wire regb_b_8;
    wire multiply_0_mult_6_3_n1;
    wire regb_b_7;
    wire multiply_0_mult_6_3_n0;
    wire multiply_0_pp_3_16;
    wire multiply_0_pp_3_15;
    wire mco_21;
    wire regb_b_10;
    wire multiply_0_mult_6_4_n1;
    wire regb_b_9;
    wire multiply_0_mult_6_4_n0;
    wire multiply_0_pp_3_18;
    wire multiply_0_pp_3_17;
    wire mco_22;
    wire regb_b_12;
    wire multiply_0_mult_6_5_n1;
    wire regb_b_11;
    wire multiply_0_mult_6_5_n0;
    wire mfco_3;
    wire multiply_0_pp_3_20;
    wire multiply_0_pp_3_19;
    wire mco_23;
    wire rega_a_6;
    wire scuba_vlo;
    wire rega_a_7;
    wire regb_b_13;
    wire multiply_0_mult_6_6_n2;
    wire scuba_vhi;
    wire multiply_0_mult_6_6_n0;

    AND2 AND2_t23 (.A(regb_b_0), .B(rega_a_0), .Z(multiply_0_pp_0_0));

    ND2 ND2_t22 (.A(regb_b_13), .B(rega_a_0), .Z(multiply_0_mult_0_6_n3));

    ND2 ND2_t21 (.A(regb_b_13), .B(rega_a_1), .Z(multiply_0_mult_0_6_n1));

    AND2 AND2_t20 (.A(regb_b_0), .B(rega_a_2), .Z(multiply_0_pp_1_2));

    ND2 ND2_t19 (.A(regb_b_13), .B(rega_a_2), .Z(multiply_0_mult_2_6_n2));

    ND2 ND2_t18 (.A(regb_b_13), .B(rega_a_3), .Z(multiply_0_mult_2_6_n1));

    AND2 AND2_t17 (.A(regb_b_0), .B(rega_a_4), .Z(multiply_0_pp_2_4));

    ND2 ND2_t16 (.A(regb_b_13), .B(rega_a_4), .Z(multiply_0_mult_4_6_n2));

    ND2 ND2_t15 (.A(regb_b_13), .B(rega_a_5), .Z(multiply_0_mult_4_6_n1));

    AND2 AND2_t14 (.A(regb_b_0), .B(rega_a_6), .Z(multiply_0_pp_3_6));

    ND2 ND2_t13 (.A(regb_b_1), .B(rega_a_7), .Z(multiply_0_mult_6_0_n1));

    ND2 ND2_t12 (.A(regb_b_0), .B(rega_a_7), .Z(multiply_0_mult_6_0_n0));

    ND2 ND2_t11 (.A(regb_b_3), .B(rega_a_7), .Z(multiply_0_mult_6_1_n1));

    ND2 ND2_t10 (.A(regb_b_2), .B(rega_a_7), .Z(multiply_0_mult_6_1_n0));

    ND2 ND2_t9 (.A(regb_b_5), .B(rega_a_7), .Z(multiply_0_mult_6_2_n1));

    ND2 ND2_t8 (.A(regb_b_4), .B(rega_a_7), .Z(multiply_0_mult_6_2_n0));

    ND2 ND2_t7 (.A(regb_b_7), .B(rega_a_7), .Z(multiply_0_mult_6_3_n1));

    ND2 ND2_t6 (.A(regb_b_6), .B(rega_a_7), .Z(multiply_0_mult_6_3_n0));

    ND2 ND2_t5 (.A(regb_b_9), .B(rega_a_7), .Z(multiply_0_mult_6_4_n1));

    ND2 ND2_t4 (.A(regb_b_8), .B(rega_a_7), .Z(multiply_0_mult_6_4_n0));

    ND2 ND2_t3 (.A(regb_b_11), .B(rega_a_7), .Z(multiply_0_mult_6_5_n1));

    ND2 ND2_t2 (.A(regb_b_10), .B(rega_a_7), .Z(multiply_0_mult_6_5_n0));

    ND2 ND2_t1 (.A(regb_b_13), .B(rega_a_6), .Z(multiply_0_mult_6_6_n2));

    ND2 ND2_t0 (.A(regb_b_12), .B(rega_a_7), .Z(multiply_0_mult_6_6_n0));

    // synopsys translate_off
    defparam FF_80.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_80 (.D(DataA[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_79.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_79 (.D(DataA[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_78.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_78 (.D(DataA[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_77.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_77 (.D(DataA[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_76.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_76 (.D(DataA[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_75.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_75 (.D(DataA[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_74.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_74 (.D(DataA[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_73.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_73 (.D(DataA[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_72.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_72 (.D(DataB[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_71.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_71 (.D(DataB[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_70.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_70 (.D(DataB[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_69.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_69 (.D(DataB[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_68.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_68 (.D(DataB[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_67.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_67 (.D(DataB[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_66.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_66 (.D(DataB[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_65.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_65 (.D(DataB[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_64.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_64 (.D(DataB[8]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_63.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_63 (.D(DataB[9]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_62.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_62 (.D(DataB[10]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_61.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_61 (.D(DataB[11]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_60.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_60 (.D(DataB[12]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_59.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_59 (.D(DataB[13]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_58.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_58 (.D(rego_o_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_57.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_57 (.D(rego_o_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_56.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_56 (.D(rego_o_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_55.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_55 (.D(rego_o_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_54.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_54 (.D(rego_o_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_53.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_53 (.D(rego_o_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_52.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_52 (.D(rego_o_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_51.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_51 (.D(rego_o_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_50.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_50 (.D(rego_o_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_49.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_49 (.D(rego_o_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_48.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_48 (.D(rego_o_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_47.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_47 (.D(rego_o_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_46.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_46 (.D(rego_o_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_45.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_45 (.D(rego_o_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_44.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_44 (.D(rego_o_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_43.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_43 (.D(rego_o_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_42.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_42 (.D(rego_o_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_41.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_41 (.D(rego_o_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_40.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_40 (.D(rego_o_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[18]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_39.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_39 (.D(rego_o_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[19]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_38.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_38 (.D(rego_o_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[20]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_37.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_37 (.D(rego_o_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[21]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_36.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_36 (.D(multiply_0_pp_0_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multiply_0_pp_0_0))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(multiply_0_pp_0_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multiply_0_pp_0_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(s_multiply_0_0_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(s_multiply_0_0_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(s_multiply_0_0_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(s_multiply_0_0_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(s_multiply_0_0_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(s_multiply_0_0_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(s_multiply_0_0_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_27 (.D(s_multiply_0_0_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_26 (.D(s_multiply_0_0_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(s_multiply_0_0_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(s_multiply_0_0_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(s_multiply_0_0_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(s_multiply_0_0_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_14))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(s_multiply_0_0_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_15))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(s_multiply_0_0_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_16))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(s_multiply_0_0_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_17))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(s_multiply_0_0_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_0_18))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(multiply_0_pp_2_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multiply_0_pp_2_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(multiply_0_pp_2_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multiply_0_pp_2_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(s_multiply_0_1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(s_multiply_0_1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(s_multiply_0_1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(s_multiply_0_1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(s_multiply_0_1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(s_multiply_0_1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(s_multiply_0_1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(s_multiply_0_1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(s_multiply_0_1_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_14))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(s_multiply_0_1_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_15))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(s_multiply_0_1_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_16))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(s_multiply_0_1_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_17))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(s_multiply_0_1_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_18))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(s_multiply_0_1_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_19))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(s_multiply_0_1_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(s_multiply_0_1_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multiply_0_1_21))
             /* synthesis GSR="ENABLED" */;

    FADD2 multiply_0_Cadd_0_7 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(scuba_vlo), 
        .B0(scuba_vlo), .CI(mfco), .COUT1(), .COUT0(), .S1(), .S0(multiply_0_pp_0_15));

    FADD2 multiply_0_Cadd_2_7 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(scuba_vlo), 
        .B0(scuba_vlo), .CI(mfco_1), .COUT1(), .COUT0(), .S1(), .S0(multiply_0_pp_1_17));

    FADD2 multiply_0_Cadd_4_7 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(scuba_vlo), 
        .B0(scuba_vlo), .CI(mfco_2), .COUT1(), .COUT0(), .S1(), .S0(multiply_0_pp_2_19));

    FADD2 multiply_0_Cadd_6_7 (.A1(scuba_vlo), .A0(scuba_vhi), .B1(scuba_vlo), 
        .B0(scuba_vlo), .CI(mfco_3), .COUT1(), .COUT0(), .S1(), .S0(multiply_0_pp_3_21));

    FADD2 multiply_0_add_0_1 (.A1(multiply_0_pp_0_3), .A0(multiply_0_pp_0_2), 
        .B1(multiply_0_pp_1_3), .B0(multiply_0_pp_1_2), .CI(scuba_vlo), 
        .COUT1(co_multiply_0_0_1), .COUT0(), .S1(s_multiply_0_0_3), .S0(s_multiply_0_0_2));

    FADD2 multiply_0_add_0_2 (.A1(multiply_0_pp_0_5), .A0(multiply_0_pp_0_4), 
        .B1(multiply_0_pp_1_5), .B0(multiply_0_pp_1_4), .CI(co_multiply_0_0_1), 
        .COUT1(co_multiply_0_0_2), .COUT0(), .S1(s_multiply_0_0_5), .S0(s_multiply_0_0_4));

    FADD2 multiply_0_add_0_3 (.A1(multiply_0_pp_0_7), .A0(multiply_0_pp_0_6), 
        .B1(multiply_0_pp_1_7), .B0(multiply_0_pp_1_6), .CI(co_multiply_0_0_2), 
        .COUT1(co_multiply_0_0_3), .COUT0(), .S1(s_multiply_0_0_7), .S0(s_multiply_0_0_6));

    FADD2 multiply_0_add_0_4 (.A1(multiply_0_pp_0_9), .A0(multiply_0_pp_0_8), 
        .B1(multiply_0_pp_1_9), .B0(multiply_0_pp_1_8), .CI(co_multiply_0_0_3), 
        .COUT1(co_multiply_0_0_4), .COUT0(), .S1(s_multiply_0_0_9), .S0(s_multiply_0_0_8));

    FADD2 multiply_0_add_0_5 (.A1(multiply_0_pp_0_11), .A0(multiply_0_pp_0_10), 
        .B1(multiply_0_pp_1_11), .B0(multiply_0_pp_1_10), .CI(co_multiply_0_0_4), 
        .COUT1(co_multiply_0_0_5), .COUT0(), .S1(s_multiply_0_0_11), .S0(s_multiply_0_0_10));

    FADD2 multiply_0_add_0_6 (.A1(multiply_0_pp_0_13), .A0(multiply_0_pp_0_12), 
        .B1(multiply_0_pp_1_13), .B0(multiply_0_pp_1_12), .CI(co_multiply_0_0_5), 
        .COUT1(co_multiply_0_0_6), .COUT0(), .S1(s_multiply_0_0_13), .S0(s_multiply_0_0_12));

    FADD2 multiply_0_add_0_7 (.A1(multiply_0_pp_0_15), .A0(multiply_0_pp_0_14), 
        .B1(multiply_0_pp_1_15), .B0(multiply_0_pp_1_14), .CI(co_multiply_0_0_6), 
        .COUT1(co_multiply_0_0_7), .COUT0(), .S1(s_multiply_0_0_15), .S0(s_multiply_0_0_14));

    FADD2 multiply_0_add_0_8 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(multiply_0_pp_1_17), 
        .B0(multiply_0_pp_1_16), .CI(co_multiply_0_0_7), .COUT1(co_multiply_0_0_8), 
        .COUT0(), .S1(s_multiply_0_0_17), .S0(s_multiply_0_0_16));

    FADD2 Cadd_multiply_0_0_9 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(scuba_vlo), 
        .B0(scuba_vlo), .CI(co_multiply_0_0_8), .COUT1(), .COUT0(), .S1(), 
        .S0(s_multiply_0_0_18));

    FADD2 multiply_0_add_1_1 (.A1(multiply_0_pp_2_7), .A0(multiply_0_pp_2_6), 
        .B1(multiply_0_pp_3_7), .B0(multiply_0_pp_3_6), .CI(scuba_vlo), 
        .COUT1(co_multiply_0_1_1), .COUT0(), .S1(s_multiply_0_1_7), .S0(s_multiply_0_1_6));

    FADD2 multiply_0_add_1_2 (.A1(multiply_0_pp_2_9), .A0(multiply_0_pp_2_8), 
        .B1(multiply_0_pp_3_9), .B0(multiply_0_pp_3_8), .CI(co_multiply_0_1_1), 
        .COUT1(co_multiply_0_1_2), .COUT0(), .S1(s_multiply_0_1_9), .S0(s_multiply_0_1_8));

    FADD2 multiply_0_add_1_3 (.A1(multiply_0_pp_2_11), .A0(multiply_0_pp_2_10), 
        .B1(multiply_0_pp_3_11), .B0(multiply_0_pp_3_10), .CI(co_multiply_0_1_2), 
        .COUT1(co_multiply_0_1_3), .COUT0(), .S1(s_multiply_0_1_11), .S0(s_multiply_0_1_10));

    FADD2 multiply_0_add_1_4 (.A1(multiply_0_pp_2_13), .A0(multiply_0_pp_2_12), 
        .B1(multiply_0_pp_3_13), .B0(multiply_0_pp_3_12), .CI(co_multiply_0_1_3), 
        .COUT1(co_multiply_0_1_4), .COUT0(), .S1(s_multiply_0_1_13), .S0(s_multiply_0_1_12));

    FADD2 multiply_0_add_1_5 (.A1(multiply_0_pp_2_15), .A0(multiply_0_pp_2_14), 
        .B1(multiply_0_pp_3_15), .B0(multiply_0_pp_3_14), .CI(co_multiply_0_1_4), 
        .COUT1(co_multiply_0_1_5), .COUT0(), .S1(s_multiply_0_1_15), .S0(s_multiply_0_1_14));

    FADD2 multiply_0_add_1_6 (.A1(multiply_0_pp_2_17), .A0(multiply_0_pp_2_16), 
        .B1(multiply_0_pp_3_17), .B0(multiply_0_pp_3_16), .CI(co_multiply_0_1_5), 
        .COUT1(co_multiply_0_1_6), .COUT0(), .S1(s_multiply_0_1_17), .S0(s_multiply_0_1_16));

    FADD2 multiply_0_add_1_7 (.A1(multiply_0_pp_2_19), .A0(multiply_0_pp_2_18), 
        .B1(multiply_0_pp_3_19), .B0(multiply_0_pp_3_18), .CI(co_multiply_0_1_6), 
        .COUT1(co_multiply_0_1_7), .COUT0(), .S1(s_multiply_0_1_19), .S0(s_multiply_0_1_18));

    FADD2 multiply_0_add_1_8 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(multiply_0_pp_3_21), 
        .B0(multiply_0_pp_3_20), .CI(co_multiply_0_1_7), .COUT1(co_multiply_0_1_8), 
        .COUT0(), .S1(s_multiply_0_1_21), .S0(s_multiply_0_1_20));

    FADD2 t_multiply_0_add_2_1 (.A1(f_s_multiply_0_0_5), .A0(f_s_multiply_0_0_4), 
        .B1(f_multiply_0_pp_2_5), .B0(f_multiply_0_pp_2_4), .CI(scuba_vlo), 
        .COUT1(co_t_multiply_0_2_1), .COUT0(), .S1(rego_o_5), .S0(rego_o_4));

    FADD2 t_multiply_0_add_2_2 (.A1(f_s_multiply_0_0_7), .A0(f_s_multiply_0_0_6), 
        .B1(f_s_multiply_0_1_7), .B0(f_s_multiply_0_1_6), .CI(co_t_multiply_0_2_1), 
        .COUT1(co_t_multiply_0_2_2), .COUT0(), .S1(rego_o_7), .S0(rego_o_6));

    FADD2 t_multiply_0_add_2_3 (.A1(f_s_multiply_0_0_9), .A0(f_s_multiply_0_0_8), 
        .B1(f_s_multiply_0_1_9), .B0(f_s_multiply_0_1_8), .CI(co_t_multiply_0_2_2), 
        .COUT1(co_t_multiply_0_2_3), .COUT0(), .S1(rego_o_9), .S0(rego_o_8));

    FADD2 t_multiply_0_add_2_4 (.A1(f_s_multiply_0_0_11), .A0(f_s_multiply_0_0_10), 
        .B1(f_s_multiply_0_1_11), .B0(f_s_multiply_0_1_10), .CI(co_t_multiply_0_2_3), 
        .COUT1(co_t_multiply_0_2_4), .COUT0(), .S1(rego_o_11), .S0(rego_o_10));

    FADD2 t_multiply_0_add_2_5 (.A1(f_s_multiply_0_0_13), .A0(f_s_multiply_0_0_12), 
        .B1(f_s_multiply_0_1_13), .B0(f_s_multiply_0_1_12), .CI(co_t_multiply_0_2_4), 
        .COUT1(co_t_multiply_0_2_5), .COUT0(), .S1(rego_o_13), .S0(rego_o_12));

    FADD2 t_multiply_0_add_2_6 (.A1(f_s_multiply_0_0_15), .A0(f_s_multiply_0_0_14), 
        .B1(f_s_multiply_0_1_15), .B0(f_s_multiply_0_1_14), .CI(co_t_multiply_0_2_5), 
        .COUT1(co_t_multiply_0_2_6), .COUT0(), .S1(rego_o_15), .S0(rego_o_14));

    FADD2 t_multiply_0_add_2_7 (.A1(f_s_multiply_0_0_17), .A0(f_s_multiply_0_0_16), 
        .B1(f_s_multiply_0_1_17), .B0(f_s_multiply_0_1_16), .CI(co_t_multiply_0_2_6), 
        .COUT1(co_t_multiply_0_2_7), .COUT0(), .S1(rego_o_17), .S0(rego_o_16));

    FADD2 t_multiply_0_add_2_8 (.A1(scuba_vlo), .A0(f_s_multiply_0_0_18), 
        .B1(f_s_multiply_0_1_19), .B0(f_s_multiply_0_1_18), .CI(co_t_multiply_0_2_7), 
        .COUT1(co_t_multiply_0_2_8), .COUT0(), .S1(rego_o_19), .S0(rego_o_18));

    FADD2 t_multiply_0_add_2_9 (.A1(scuba_vlo), .A0(scuba_vlo), .B1(f_s_multiply_0_1_21), 
        .B0(f_s_multiply_0_1_20), .CI(co_t_multiply_0_2_8), .COUT1(co_t_multiply_0_2_9), 
        .COUT0(), .S1(rego_o_21), .S0(rego_o_20));

    MULT2 multiply_0_mult_0_0 (.A0(regb_b_0), .A1(regb_b_1), .A2(regb_b_1), 
        .A3(regb_b_2), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(scuba_vlo), .P0(multiply_0_pp_0_1), .P1(multiply_0_pp_0_2), 
        .CO(mco));

    MULT2 multiply_0_mult_0_1 (.A0(regb_b_2), .A1(regb_b_3), .A2(regb_b_3), 
        .A3(regb_b_4), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(mco), .P0(multiply_0_pp_0_3), .P1(multiply_0_pp_0_4), .CO(mco_1));

    MULT2 multiply_0_mult_0_2 (.A0(regb_b_4), .A1(regb_b_5), .A2(regb_b_5), 
        .A3(regb_b_6), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(mco_1), .P0(multiply_0_pp_0_5), .P1(multiply_0_pp_0_6), .CO(mco_2));

    MULT2 multiply_0_mult_0_3 (.A0(regb_b_6), .A1(regb_b_7), .A2(regb_b_7), 
        .A3(regb_b_8), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(mco_2), .P0(multiply_0_pp_0_7), .P1(multiply_0_pp_0_8), .CO(mco_3));

    MULT2 multiply_0_mult_0_4 (.A0(regb_b_8), .A1(regb_b_9), .A2(regb_b_9), 
        .A3(regb_b_10), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(mco_3), .P0(multiply_0_pp_0_9), .P1(multiply_0_pp_0_10), .CO(mco_4));

    MULT2 multiply_0_mult_0_5 (.A0(regb_b_10), .A1(regb_b_11), .A2(regb_b_11), 
        .A3(regb_b_12), .B0(rega_a_1), .B1(rega_a_0), .B2(rega_a_1), .B3(rega_a_0), 
        .CI(mco_4), .P0(multiply_0_pp_0_11), .P1(multiply_0_pp_0_12), .CO(mco_5));

    MULT2 multiply_0_mult_0_6 (.A0(regb_b_12), .A1(regb_b_13), .A2(multiply_0_mult_0_6_n1), 
        .A3(multiply_0_mult_0_6_n3), .B0(rega_a_1), .B1(rega_a_0), .B2(scuba_vhi), 
        .B3(scuba_vhi), .CI(mco_5), .P0(multiply_0_pp_0_13), .P1(multiply_0_pp_0_14), 
        .CO(mfco));

    MULT2 multiply_0_mult_2_0 (.A0(regb_b_0), .A1(regb_b_1), .A2(regb_b_1), 
        .A3(regb_b_2), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(scuba_vlo), .P0(multiply_0_pp_1_3), .P1(multiply_0_pp_1_4), 
        .CO(mco_6));

    MULT2 multiply_0_mult_2_1 (.A0(regb_b_2), .A1(regb_b_3), .A2(regb_b_3), 
        .A3(regb_b_4), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(mco_6), .P0(multiply_0_pp_1_5), .P1(multiply_0_pp_1_6), .CO(mco_7));

    MULT2 multiply_0_mult_2_2 (.A0(regb_b_4), .A1(regb_b_5), .A2(regb_b_5), 
        .A3(regb_b_6), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(mco_7), .P0(multiply_0_pp_1_7), .P1(multiply_0_pp_1_8), .CO(mco_8));

    MULT2 multiply_0_mult_2_3 (.A0(regb_b_6), .A1(regb_b_7), .A2(regb_b_7), 
        .A3(regb_b_8), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(mco_8), .P0(multiply_0_pp_1_9), .P1(multiply_0_pp_1_10), .CO(mco_9));

    MULT2 multiply_0_mult_2_4 (.A0(regb_b_8), .A1(regb_b_9), .A2(regb_b_9), 
        .A3(regb_b_10), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(mco_9), .P0(multiply_0_pp_1_11), .P1(multiply_0_pp_1_12), .CO(mco_10));

    MULT2 multiply_0_mult_2_5 (.A0(regb_b_10), .A1(regb_b_11), .A2(regb_b_11), 
        .A3(regb_b_12), .B0(rega_a_3), .B1(rega_a_2), .B2(rega_a_3), .B3(rega_a_2), 
        .CI(mco_10), .P0(multiply_0_pp_1_13), .P1(multiply_0_pp_1_14), .CO(mco_11));

    MULT2 multiply_0_mult_2_6 (.A0(regb_b_12), .A1(multiply_0_mult_2_6_n2), 
        .A2(multiply_0_mult_2_6_n1), .A3(scuba_vlo), .B0(rega_a_3), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(rega_a_2), .CI(mco_11), .P0(multiply_0_pp_1_15), 
        .P1(multiply_0_pp_1_16), .CO(mfco_1));

    MULT2 multiply_0_mult_4_0 (.A0(regb_b_0), .A1(regb_b_1), .A2(regb_b_1), 
        .A3(regb_b_2), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(scuba_vlo), .P0(multiply_0_pp_2_5), .P1(multiply_0_pp_2_6), 
        .CO(mco_12));

    MULT2 multiply_0_mult_4_1 (.A0(regb_b_2), .A1(regb_b_3), .A2(regb_b_3), 
        .A3(regb_b_4), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(mco_12), .P0(multiply_0_pp_2_7), .P1(multiply_0_pp_2_8), .CO(mco_13));

    MULT2 multiply_0_mult_4_2 (.A0(regb_b_4), .A1(regb_b_5), .A2(regb_b_5), 
        .A3(regb_b_6), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(mco_13), .P0(multiply_0_pp_2_9), .P1(multiply_0_pp_2_10), .CO(mco_14));

    MULT2 multiply_0_mult_4_3 (.A0(regb_b_6), .A1(regb_b_7), .A2(regb_b_7), 
        .A3(regb_b_8), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(mco_14), .P0(multiply_0_pp_2_11), .P1(multiply_0_pp_2_12), .CO(mco_15));

    MULT2 multiply_0_mult_4_4 (.A0(regb_b_8), .A1(regb_b_9), .A2(regb_b_9), 
        .A3(regb_b_10), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(mco_15), .P0(multiply_0_pp_2_13), .P1(multiply_0_pp_2_14), .CO(mco_16));

    MULT2 multiply_0_mult_4_5 (.A0(regb_b_10), .A1(regb_b_11), .A2(regb_b_11), 
        .A3(regb_b_12), .B0(rega_a_5), .B1(rega_a_4), .B2(rega_a_5), .B3(rega_a_4), 
        .CI(mco_16), .P0(multiply_0_pp_2_15), .P1(multiply_0_pp_2_16), .CO(mco_17));

    MULT2 multiply_0_mult_4_6 (.A0(regb_b_12), .A1(multiply_0_mult_4_6_n2), 
        .A2(multiply_0_mult_4_6_n1), .A3(scuba_vlo), .B0(rega_a_5), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(rega_a_4), .CI(mco_17), .P0(multiply_0_pp_2_17), 
        .P1(multiply_0_pp_2_18), .CO(mfco_2));

    MULT2 multiply_0_mult_6_0 (.A0(multiply_0_mult_6_0_n0), .A1(regb_b_1), 
        .A2(multiply_0_mult_6_0_n1), .A3(regb_b_2), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(scuba_vhi), .P0(multiply_0_pp_3_7), 
        .P1(multiply_0_pp_3_8), .CO(mco_18));

    MULT2 multiply_0_mult_6_1 (.A0(multiply_0_mult_6_1_n0), .A1(regb_b_3), 
        .A2(multiply_0_mult_6_1_n1), .A3(regb_b_4), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(mco_18), .P0(multiply_0_pp_3_9), 
        .P1(multiply_0_pp_3_10), .CO(mco_19));

    MULT2 multiply_0_mult_6_2 (.A0(multiply_0_mult_6_2_n0), .A1(regb_b_5), 
        .A2(multiply_0_mult_6_2_n1), .A3(regb_b_6), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(mco_19), .P0(multiply_0_pp_3_11), 
        .P1(multiply_0_pp_3_12), .CO(mco_20));

    MULT2 multiply_0_mult_6_3 (.A0(multiply_0_mult_6_3_n0), .A1(regb_b_7), 
        .A2(multiply_0_mult_6_3_n1), .A3(regb_b_8), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(mco_20), .P0(multiply_0_pp_3_13), 
        .P1(multiply_0_pp_3_14), .CO(mco_21));

    MULT2 multiply_0_mult_6_4 (.A0(multiply_0_mult_6_4_n0), .A1(regb_b_9), 
        .A2(multiply_0_mult_6_4_n1), .A3(regb_b_10), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(mco_21), .P0(multiply_0_pp_3_15), 
        .P1(multiply_0_pp_3_16), .CO(mco_22));

    MULT2 multiply_0_mult_6_5 (.A0(multiply_0_mult_6_5_n0), .A1(regb_b_11), 
        .A2(multiply_0_mult_6_5_n1), .A3(regb_b_12), .B0(scuba_vhi), .B1(rega_a_6), 
        .B2(scuba_vhi), .B3(rega_a_6), .CI(mco_22), .P0(multiply_0_pp_3_17), 
        .P1(multiply_0_pp_3_18), .CO(mco_23));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    MULT2 multiply_0_mult_6_6 (.A0(multiply_0_mult_6_6_n0), .A1(multiply_0_mult_6_6_n2), 
        .A2(regb_b_13), .A3(scuba_vlo), .B0(scuba_vhi), .B1(scuba_vhi), 
        .B2(rega_a_7), .B3(rega_a_6), .CI(mco_23), .P0(multiply_0_pp_3_19), 
        .P1(multiply_0_pp_3_20), .CO(mfco_3));

    assign rego_o_0 = f_multiply_0_pp_0_0;
    assign rego_o_1 = f_multiply_0_pp_0_1;
    assign rego_o_2 = f_s_multiply_0_0_2;
    assign rego_o_3 = f_s_multiply_0_0_3;


    // exemplar begin
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
