/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 4.8 */
/* Thu Mar 05 11:22:52 2015 */

/* parameterized module instance */
multiply __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
