/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.4.0.80 */
/* Module Version: 1.5 */
/* Thu Mar 05 14:17:05 2015 */

/* parameterized module instance */
quad_table __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), 
    .Cosine( ));
