/* Verilog module instantiation template generated by SCUBA Diamond_3.0_Production (94) */
/* Module Version: 5.5 */
/* Fri Feb 07 08:39:47 2014 */

/* parameterized module instance */
DataFIFO __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
