

// DATE:     22.11.2013 12:55:00 
// TITLE:    
// MODULE:   sr24bit
// DESIGN:   sr24bit
// FILENAME: sr24bit.v
// PROJECT:  
// VERSION:  1.0
//
// This file is generated by verilog template from schematic symbol.
// The logic can be added into the generated HDL file by user. 


`timescale 1 ns / 1 ns

module sr24bit(DIN, SCLK, nSYNC, Q);
// Inputs
	input nSYNC;
	input DIN;
	input SCLK;


// Outputs
	output [23:0] Q;

// Input Data Types 
	wire nSYNC, DIN, SCLK;
// Output Data Types 
	reg [23:0] Q=0;

// Internal Variables

// ### Code Start ###

/*
always@(negedge nSYNC)

	Q[23:0]	<= 0;
*/
always@(posedge SCLK)// or negedge nSYNC)

	
	if (nSYNC == 1)
		Q[23:0]	<= Q[23:0];
	else 
    begin
		Q[23:1]	<= Q[22:0];
		Q[0]	<= DIN;
	end		


endmodule // sr24bit
