

// DATE:     29.02.2008 10:09:50 
// TITLE:    
// MODULE:   sr32bit
// DESIGN:   sr32bit
// FILENAME: sr32bit.v
// PROJECT:  
// VERSION:  1.0
//
// This file is generated by verilog template from schematic symbol.
// The logic can be added into the generated HDL file by user. 


`timescale 1 ns / 1 ns

module sr32bit(DIN, SCLK, nSYNC, Q);
// Inputs
	input nSYNC;
	input DIN;
	input SCLK;


// Outputs
	output [31:0] Q;

// Input Data Types 
	wire nSYNC, DIN, SCLK;
// Output Data Types 
	reg [31:0] Q=0;

// Internal Variables

// ### Code Start ###

/*
always@(negedge nSYNC)

	Q[31:0]	<= 0;
*/
always@(posedge SCLK)// or negedge nSYNC)

	
	if (nSYNC == 1)
		Q[31:0]	<= Q[31:0];
	else 
    begin
		Q[31:1]	<= Q[30:0];
		Q[0]	<= DIN;
	end		


endmodule // sr32bit
