/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.5.1.302 */
/* Module Version: 5.8 */
/* Mon Sep 14 13:24:39 2015 */

/* parameterized module instance */
FIFO_OUT __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ), .AlmostEmpty( ), 
    .AlmostFull( ));
