/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.5.1.302 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.5_x64\ispfpga\bin\nt64\scuba.exe -w -n FIFO_OUT -lang verilog -synth synplify -bb -arch xo2c00 -type ebfifo -depth 4096 -width 16 -rwidth 8 -regout -resetmode ASYNC -reset_rel ASYNC -no_enable -pe 256 -pf 4000  */
/* Mon Sep 14 13:24:39 2015 */


`timescale 1 ns / 1 ps
module FIFO_OUT (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire Empty_int;
    wire Full_int;
    wire scuba_vhi;
    wire scuba_vlo;

    defparam FIFO_OUT_0_7.FULLPOINTER1 = "0b01111111111110" ;
    defparam FIFO_OUT_0_7.FULLPOINTER = "0b10000000000000" ;
    defparam FIFO_OUT_0_7.AFPOINTER1 = "0b01111100111110" ;
    defparam FIFO_OUT_0_7.AFPOINTER = "0b01111101000000" ;
    defparam FIFO_OUT_0_7.AEPOINTER1 = "0b00000100000001" ;
    defparam FIFO_OUT_0_7.AEPOINTER = "0b00000100000000" ;
    defparam FIFO_OUT_0_7.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_0_7.GSR = "DISABLED" ;
    defparam FIFO_OUT_0_7.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_0_7.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_0_7.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_0_7.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_0_7.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_0_7.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_0_7 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[0]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[8]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[0]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    defparam FIFO_OUT_1_6.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_1_6.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_1_6.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_1_6.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_1_6.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_1_6.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_1_6.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_1_6.GSR = "DISABLED" ;
    defparam FIFO_OUT_1_6.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_1_6.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_1_6.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_1_6.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_1_6.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_1_6.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_1_6 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[1]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[9]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[1]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[1]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam FIFO_OUT_2_5.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_2_5.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_2_5.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_2_5.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_2_5.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_2_5.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_2_5.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_2_5.GSR = "DISABLED" ;
    defparam FIFO_OUT_2_5.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_2_5.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_2_5.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_2_5.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_2_5.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_2_5.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_2_5 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[2]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[10]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[2]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[2]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam FIFO_OUT_3_4.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_3_4.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_3_4.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_3_4.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_3_4.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_3_4.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_3_4.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_3_4.GSR = "DISABLED" ;
    defparam FIFO_OUT_3_4.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_3_4.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_3_4.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_3_4.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_3_4.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_3_4.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_3_4 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[3]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[11]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[3]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[3]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam FIFO_OUT_4_3.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_4_3.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_4_3.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_4_3.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_4_3.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_4_3.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_4_3.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_4_3.GSR = "DISABLED" ;
    defparam FIFO_OUT_4_3.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_4_3.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_4_3.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_4_3.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_4_3.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_4_3.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_4_3 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[4]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[12]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[4]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[4]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam FIFO_OUT_5_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_5_2.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_5_2.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_5_2.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_5_2.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_5_2.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_5_2.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_5_2.GSR = "DISABLED" ;
    defparam FIFO_OUT_5_2.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_5_2.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_5_2.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_5_2.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_5_2.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_5_2.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_5_2 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[5]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[13]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[5]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[5]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    defparam FIFO_OUT_6_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_6_1.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_6_1.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_6_1.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_6_1.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_6_1.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_6_1.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_6_1.GSR = "DISABLED" ;
    defparam FIFO_OUT_6_1.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_6_1.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_6_1.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_6_1.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_6_1.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_6_1.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_6_1 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[6]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[14]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[6]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[6]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam FIFO_OUT_7_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_7_0.FULLPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_7_0.AFPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_7_0.AFPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_7_0.AEPOINTER1 = "0b00000000000000" ;
    defparam FIFO_OUT_7_0.AEPOINTER = "0b11111111111111" ;
    defparam FIFO_OUT_7_0.ASYNC_RESET_RELEASE = "ASYNC" ;
    defparam FIFO_OUT_7_0.GSR = "DISABLED" ;
    defparam FIFO_OUT_7_0.RESETMODE = "ASYNC" ;
    defparam FIFO_OUT_7_0.REGMODE = "OUTREG" ;
    defparam FIFO_OUT_7_0.CSDECODE_R = "0b11" ;
    defparam FIFO_OUT_7_0.CSDECODE_W = "0b11" ;
    defparam FIFO_OUT_7_0.DATA_WIDTH_R = 1 ;
    defparam FIFO_OUT_7_0.DATA_WIDTH_W = 2 ;
    FIFO8KB FIFO_OUT_7_0 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[7]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[15]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[7]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(RdEn), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(scuba_vhi), .ORE(scuba_vhi), 
        .CLKW(WrClock), .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[7]), 
        .DO1(), .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), 
        .DO9(), .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), 
        .DO17(), .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
